### ISSUE TITLE
make this private

### ISSUE THREAD

**Issue by smacke** [christian-mann/compilers#4]
I want people at TU to suffer the way I never did.

**Comment by smacke** [comment]
In all seriousness, I can guarantee you people are going to find this and copy+paste, or at least reverse engineer how to do stuff rather than figuring it out themselves. I get the impression that these projects are among the more significant in terms of implementation difficulty and that a lot of learning takes place, and publicly hosting this code undermines that. (Maybe the learning is not necessarily directly toward compilers as e.g. writing a parser from scratch is quite tedious, but I imagine there's at least quite a bit in terms of debugging techniques and how to not shoot oneself in the foot.)

Why do I care about this... obviously I've been TAing for too long.

**Comment by christian-mann** [comment]
I asked github for some private repositories recently for being a college student; they haven't seem to come through yet; it's odd.

Moved it to a private repository on BitBucket until then.
